### ISSUE TITLE
Unable to install npm packages

### ISSUE THREAD

**Issue by AmitJoki** [berkmancenter/question_tool#76]
I keep getting the error: 
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fibers@1.0.13 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fibers@1.0.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

I have Node 8.9.4 LTS and am on Ubuntu 16.0.4 Xenial Xerus.

**Comment by Salil-Jain** [comment]
Did you try installing it with another version of node as given [here](https://github.com/meteor/meteor/issues/7983)? You  can use nvm to switch between different versions of node ([more info](https://www.sitepoint.com/quick-tip-multiple-versions-node-nvm/))

**Comment by AmitJoki** [comment]
@Salil-Jain yeah that seems to be working. Thanks!
